### ISSUE TITLE
plist string 

### ISSUE THREAD

**Issue by pimpc1703** [iabem97/houdini_issues#3]
comes to the end and it dose this https://gyazo.com/9a7f83c5321e60b96968dce13785fb4a    is this normal?

**Comment by Kerabyte** [comment]
Well, I got that error as well, but it didn't seem to affect anything. [Other people](https://forum.kodi.tv/showthread.php?tid=319912) have also had this issue before Houdini, so I'm pretty sure it's fine.

**Comment by Cryptiiiic** [comment]
@pimpc1703 Close the issue. This is nothing to do with Houdini. This happens with impactor. The app still installs even with this error.
