### ISSUE TITLE
Not working with 6s+ 10.3.1  

### ISSUE THREAD

**Issue by RuesanG** [iabem97/houdini_issues#9]
Houdini its not working im rebooted my phone im put a airplane mode im wating a app 1-2 min and click starts and failed 

ps my english is soooooooo baaad :)

**Comment by d0ppl3r** [comment]
It's working,u just need TODO it #AgainAndAgain.

**Comment by kingjamonte** [comment]
keep doing it

**Comment by RuesanG** [comment]
sry really not works

**Comment by Cryptiiiic** [comment]
Guys please press the ? button in the top right corner and read the popup. It tells you what to do to get it to work.

**Comment by Cryptiiiic** [comment]
Guys please press the ? button in the top right corner and read the popup. It tells you what to do to get it to work. @RuesanG
